name: ARM CI Build

on:
  push:
    branches:
      - main
      - master
      - full-feetech-api
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux_arm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [armv7, aarch64]  # 仅编译 ARM 架构
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build ARM wheel
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter
          manylinux: auto
          sccache: false  # 强制禁用 sccache

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel-arm-${{ matrix.target }}
          path: dist
          retention-days: 7  # 设置 artifacts 保留天数（可选）
